name: 08 - variables

on:
    workflow_dispatch:
env:
    WORKFLOW_VAR: "I am a workflow env variable"
    OVERWRITTEN: 'I will be overwritten'

jobs:
    echo:
       runs-on: ubuntu-latest
       env:
           JOB_VAR: "I am a job env variable"
           OVERWRITTEN: 'I have been overwritten'
       steps:
         - name: Echo Variables
           env:
              STEP_VAR: "I am a step env variable"
              step_var2: "I am another step env variable"
           run: |
              echo "STEP ENV var : ${{ env.STEP_VAR }}"
              echo "step_var2: $step_var2"
              echo "JOB ENV var : ${{ env.JOB_VAR }}"
              echo "Workflow ENV var : ${{ env.WORKFLOW_VAR }}"
              echo "overwritten var : ${{ env.OVERWRITTEN }}"
         - name: overwritten
           env:
                OVERWRITTEN: 'I am the last overwritten at the step level'
           run: |

              echo "overwritten var : ${{ env.OVERWRITTEN }}"
